name: ez_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/gz_gaming_logo.png
    - assets/diamond_icon.png
    - assets/dana_logo.png
    - assets/bca_logo.png
    - assets/qris_logo.png
    - assets/pembayaran_qris.png
    - assets/10_MLBB_NewDemom.png
    - assets/50_MLBB_NewDemom.png
    - assets/150x250_MLBB_NewDemom.png
    - assets/500_MLBB_NewDemom.png
    - assets/1500_MLBB_NewDemom.png
    - assets/2500_MLBB_NewDemom.png
